const orderCopy={
 fa:{add:"افزودن به سفارش",cart:"مشاهده سفارش",title:"سفارش شما",empty:"هنوز نوشیدنی انتخاب نکرده‌اید.",name:"نام شما",phone:"شماره تماس",time:"زمان دریافت",iced:"به صورت آیس (+۲۰ هزار تومان)",total:"مجموع تقریبی",send:"ارسال سفارش در واتساپ",unit:"هزار تومان",note:"پیام سفارش کپی می‌شود؛ سپس آن را در گفت‌وگوی واتساپ ارسال کنید.",required:"لطفاً نام و زمان دریافت را وارد کنید.",newOrder:"سفارش جدید قهوه‌چی",pickup:"زمان دریافت",customer:"نام",contact:"تماس"},
 ar:{add:"أضف إلى الطلب",cart:"عرض الطلب",title:"طلبك",empty:"لم تختر أي مشروب بعد.",name:"الاسم",phone:"رقم الاتصال",time:"وقت الاستلام",iced:"بارد (+٢٠ ألف تومان)",total:"المجموع التقريبي",send:"إرسال عبر واتساب",unit:"ألف تومان",note:"سيتم نسخ الطلب؛ أرسله بعد فتح محادثة واتساب.",required:"يرجى إدخال الاسم ووقت الاستلام.",newOrder:"طلب جديد من قهوجي",pickup:"وقت الاستلام",customer:"الاسم",contact:"الاتصال"},
 en:{add:"Add to order",cart:"View order",title:"Your order",empty:"You haven’t selected a drink yet.",name:"Your name",phone:"Phone number",time:"Pickup time",iced:"Make it iced (+20,000 tomans)",total:"Estimated total",send:"Send order on WhatsApp",unit:"thousand tomans",note:"Your order will be copied; paste and send it in the WhatsApp chat.",required:"Please enter your name and pickup time.",newOrder:"New Ghahvechi order",pickup:"Pickup time",customer:"Customer",contact:"Contact"}
};
let order=[];
const orderBar=document.createElement("button");orderBar.className="order-bar";orderBar.hidden=true;
const orderDialog=document.createElement("dialog");orderDialog.className="order-dialog";
document.body.append(orderBar,orderDialog);
const currentLang=()=>document.body.dataset.lang||"fa";
const parsePrice=value=>{const normalized=String(value).replace(/[۰-۹]/g,d=>"۰۱۲۳۴۵۶۷۸۹".indexOf(d)).replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d));const nums=normalized.match(/\d+/g);return nums?Number(nums[nums.length-1]):0};
const faNumber=value=>Number(value).toLocaleString("fa-IR");
function persianDrinkName(id){const [sectionIndex,itemIndex]=id.split("-").map(Number);return catalog.fa.sections[sectionIndex]?.[3]?.[itemIndex]?.[0]||id}
function availableDrinks(){const t=catalog[currentLang()];return t.sections.flatMap((s,si)=>si===1||si===3||si===4?s[3].map((item,ii)=>({id:`${si}-${ii}`,name:item[0],price:parsePrice(item[2]),range:item[2]})):[])}
function addOrder(id){const drink=availableDrinks().find(d=>d.id===id);if(!drink)return;const found=order.find(x=>x.id===id);found?found.qty++:order.push({...drink,qty:1,iced:false});paintOrder();}
function paintButtons(){document.querySelectorAll(".order-add").forEach(b=>b.remove());const labels=orderCopy[currentLang()];Object.entries({arabic:1,classic:3,hot:4}).forEach(([section,si])=>{document.querySelectorAll(`#${section} .items article`).forEach((row,itemIndex)=>{const button=document.createElement("button");button.className="order-add";button.type="button";button.dataset.orderId=`${si}-${itemIndex}`;button.setAttribute("aria-label",labels.add);button.title=labels.add;button.textContent="+";row.append(button)})});}
function paintOrder(){const l=orderCopy[currentLang()];const count=order.reduce((n,x)=>n+x.qty,0);orderBar.hidden=!count;orderBar.innerHTML=`<span>${l.cart}</span><span class="order-count">${count}</span>`;if(!orderDialog.open)return;openOrder();}
function openOrder(){const l=orderCopy[currentLang()];const dir=catalog[currentLang()].dir;const total=order.reduce((n,x)=>n+(x.price+(x.iced?20:0))*x.qty,0);orderDialog.dir=dir;orderDialog.innerHTML=`<div class="order-dialog__inner"><div class="order-dialog__head"><h2>${l.title}</h2><button class="order-close" aria-label="Close">×</button></div>${order.length?`<div class="order-lines">${order.map(x=>`<article class="order-line" data-id="${x.id}"><div><h3>${x.name}</h3><p>${x.range} ${l.unit}</p></div><div class="order-controls"><button data-action="minus">−</button><output>${x.qty}</output><button data-action="plus">+</button></div></article>`).join("")}</div><form class="order-form"><div class="order-fields"><label>${l.name}<input name="name" autocomplete="name" required></label><label>${l.phone}<input name="phone" type="tel" autocomplete="tel"></label><label>${l.time}<input name="time" type="time" required></label><label class="iced-field"><input name="iced" type="checkbox"><span>${l.iced}</span></label></div><div class="order-total"><span>${l.total}</span><strong>${total.toLocaleString(currentLang()==="en"?"en-US":"fa-IR")} ${l.unit}</strong></div><button class="order-submit" type="submit">${l.send}</button><p class="order-note">${l.note}</p></form>`:`<p class="order-empty">${l.empty}</p>`}</div>`;if(!orderDialog.open)orderDialog.showModal();}
orderBar.onclick=openOrder;
document.addEventListener("click",e=>{const add=e.target.closest(".order-add");if(add)addOrder(add.dataset.orderId);if(e.target.closest(".order-close"))orderDialog.close();const control=e.target.closest("[data-action]");if(control){const line=control.closest(".order-line"),item=order.find(x=>x.id===line.dataset.id);if(item){item.qty+=control.dataset.action==="plus"?1:-1;if(item.qty<1)order=order.filter(x=>x!==item);openOrder();paintOrder()}}});
orderDialog.addEventListener("click",e=>{if(e.target===orderDialog)orderDialog.close()});
orderDialog.addEventListener("change",e=>{if(e.target.name==="iced"){order.forEach(x=>x.iced=e.target.checked);openOrder()}});
orderDialog.addEventListener("submit",e=>{e.preventDefault();const l=orderCopy[currentLang()],data=new FormData(e.target),name=data.get("name"),time=data.get("time"),phone=data.get("phone");if(!name||!time){alert(l.required);return}const total=order.reduce((n,x)=>n+(x.price+(x.iced?20:0))*x.qty,0);const lines=["سفارش جدید قهوه‌چی","",`نام مشتری: ${name}`,phone?`شماره تماس: ${phone}`:"",`زمان دریافت: ${time}`,"",...order.map(x=>`${faNumber(x.qty)} × ${persianDrinkName(x.id)}${x.iced?" — آیس":""} — ${faNumber((x.price+(x.iced?20:0))*x.qty)} هزار تومان`),"",`مجموع تقریبی: ${faNumber(total)} هزار تومان`].filter(Boolean);navigator.clipboard.writeText(lines.join("\n")).catch(()=>{});window.open("https://wa.me/qr/32Y7ITF6VB4IJ1","_blank","noopener,noreferrer")});
const originalRender=render;render=function(lang){originalRender(lang);requestAnimationFrame(()=>{paintButtons();paintOrder()})};
render(localStorage.getItem("coffee-language")||"fa");
